language: ruby
rvm:
  - 2.2.3

branches:
  only:
    - source

script: 
  - rake generate

deploy:
  provider: pages
  local_dir: public
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: source
