language: ruby
rvm:
  - 2.2.3

script: 
  - rake generate

deploy:
  provider: pages
  local_dir: _delpoy
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: source
